name: Run Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch: # For manual run
    inputs:
      run_tests:
        description: 'Select which tests to run'
        required: true
        default: 'full'
        type: string
  schedule:
    - cron: "0 0 * * *" # Nightly at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

      - name: Run full test suite
        if: github.event.inputs.run_tests == 'full' || github.event.inputs.run_tests == ''
        run: |
          pytest --maxfail=5 --disable-warnings

      - name: Run specific tests
        if: github.event.inputs.run_tests == 'test_case_5_6'
        run: |
          pytest -k "test_compare_stock_symbols"
